version: "2"
services:
  webserver:
    image: test-bun-ssr
    ports:
      - "3000:3000"
    environment:
      WEB_SERVER_PORT: 3000
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public